
<!-- ## install Xampp
   # Start Apache Server
   # Go to -> C:\xampp\htdocs\ - create a folder
   # open folder in code editor (eg:VS Code, Atom etc..)
   # create a file name + extention .php
## For Output
   # open browser http://localhost/folder_name/file-name.PHP -->
<?php
  echo "Hello World..", "<br>";
  echo ("hai this is PHP");

  print "Hello Every one <br>";
//   echo can take multiple parameters, separated by commas, and it can handle multiple expressions at once.
  echo "My Name is " , "john";
//print can only take one argument.
  print "only one argument/value";
  
//HTML tage in php
  echo "<h1>", "HTML tag in PHP", "</h1>"    
?>